# Generated by Django 6.0 on 2025-12-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='fee_type',
            field=models.CharField(choices=[('DUES', 'Hall Dues'), ('FINE', 'Damages/Fine'), ('UTIL', 'Utility Charge')], default='DUES', max_length=10),
        ),
    ]
