# Generated by Django 6.0 on 2025-12-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_fee_fee_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('RENT', 'Hostel rent'), ('FEES', 'Additional Fees')], default='RENT', max_length=10),
        ),
    ]
