# Generated by Django 6.0 on 2025-12-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_alter_hostel_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='number_of_rooms',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
