# Generated by Django 6.0 on 2025-12-21 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_hostel_number_of_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='block',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hostel.hostel'),
        ),
        migrations.CreateModel(
            name='RoomPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(help_text="e.g. 1 for '1 in a room', 2 for '2 in a room'")),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hostels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='hostel.hostel')),
            ],
            options={
                'unique_together': {('hostels', 'capacity')},
            },
        ),
    ]
