# Generated by Django 6.0 on 2025-12-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_hostelmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reference',
            field=models.CharField(default='-', max_length=50),
            preserve_default=False,
        ),
    ]
