# Generated by Django 6.0 on 2025-12-21 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_alter_room_block_alter_room_hostel_roompricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='hostel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostel.hostel'),
        ),
    ]
