# Generated by Django 6.0 on 2025-12-22 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0005_alter_student_hostel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='hostel',
        ),
        migrations.AddField(
            model_name='student',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='hostel.room'),
        ),
    ]
