# Generated by Django 6.0 on 2025-12-22 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0006_remove_student_hostel_student_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roompricing',
            old_name='hostels',
            new_name='hostel',
        ),
        migrations.AlterUniqueTogether(
            name='roompricing',
            unique_together={('hostel', 'capacity')},
        ),
    ]
