# Generated by Django 6.0 on 2025-12-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0007_rename_hostels_roompricing_hostel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('hostel', 'room_number')},
        ),
    ]
